#!/bin/zsh
REMOTE_URL="https://thdndpk-svg.github.io/k-stock-force-tracker/"
LOG_DIR="$HOME/Library/Logs"
mkdir -p "$LOG_DIR"
/usr/bin/open "$REMOTE_URL" >> "$LOG_DIR/KStockForceTracker.log" 2>&1
exit $?
